baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'demo 1'
theme = 'my theme'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
tag = "tags"
category = "categories"
album = "albums"
artist = "artists"